name: island
version: '0.1'
maintainer: SimSpace
license: AllRightsReserved

default-extensions:
  - AllowAmbiguousTypes
  - ConstraintKinds
  - DefaultSignatures
  - FlexibleContexts
  - MultiParamTypeClasses
  - ScopedTypeVariables
  - TypeApplications
  - TypeFamilies
  - UndecidableInstances

ghc-options:
  - -Wall
  - -Werror
  - -fwarn-tabs
  - -O2

dependencies:
  - base
  - generics-eot
  - mtl

library:
  source-dirs: src
