name: island
version: '0.1'
maintainer: SimSpace
license: AllRightsReserved

default-extensions:
  - AllowAmbiguousTypes
  - ConstraintKinds
  - MultiParamTypeClasses
  - ScopedTypeVariables
  - TypeFamilies

ghc-options:
  - -Wall
  - -Werror
  - -fwarn-tabs
  - -O2

dependencies:
  - base

library:
  source-dirs: src
