name: island
version: '0.1'
maintainer: SimSpace
license: AllRightsReserved

default-extensions:
  - ConstraintKinds
  - DefaultSignatures
  - FlexibleContexts
  - MultiParamTypeClasses
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TemplateHaskell
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - UndecidableInstances

ghc-options:
  - -Wall
  - -Werror
  - -fwarn-tabs
  - -O2

dependencies:
  - base
  - containers
  - extra
  - generics-eot
  - lens
  - mtl
  - template-haskell
  - text
  - th-utilities
  - transformers

library:
  source-dirs: src
